#!/bin/bash

echo starting mockservice
npx json-server --watch /Users/taaelhu2/private/private_projects/frontend/sdx-frontend/db.json --routes /Users/taaelhu2/private/private_projects/frontend/sdx-frontend/routes.json;